name: mlmvn
channels:
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - python=3.9.13
  - ipython=8.4
  - ipywidgets=7.7.1
  - ipykernel=6.15.1
  - fastcore=1.5.16
  - jupyter=1.0.0
  - nbdev=2.1.3
  - pandas=1.4.3    
  - matplotlib=3.5.2
  - numpy=1.23.1
