name: mlmvn
channels:
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipywidgets=7.7.1
  - jupyter=1.0.0
  - nbdev=2.1.3
  - numpy=1.23.1
  - pandas=1.4.3
  - pre_commit=2.20.0
  - pillow=9.2.0
  - python=3.9.13
  - pytorch=1.12.1
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.2.2
  - matplotlib=3.5.3
  - seaborn=0.12.0
