# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_optim.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_optim.ipynb 3
import math
import torch
import torch.nn as nn
from torch.autograd import Function

# %% ../nbs/02_optim.ipynb 4
#|export

