# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_process.ipynb.

# %% auto 0
__all__ = ['angle2class']

# %% ../nbs/04_process.ipynb 2
import torch
import numpy as np

# %% ../nbs/04_process.ipynb 3
def angle2class(x: torch.tensor, categories: int, periodicity: int) -> torch.tensor:
    tmp = x.angle() + 2 * np.pi
    angle = torch.remainder(tmp, 2 * np.pi)

    # This will be the discrete output (the number of sector)
    o = torch.floor(categories * periodicity * angle / (2 * np.pi))
    return torch.remainder(o, categories)
