ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "mlmvn"
  site-url: "https://antonpf.github.io/mlmvn/"
  description: ""
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/antonpf/mlmvn/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/antonpf/mlmvn/"
  sidebar:
    style: "floating"

metadata-files:
  - sidebar.yml
  - custom.yml
